homework4 v2.0
ferr311/Movies_AA pull request #4
Opened 2020-12-03 14:39 UTC by ferr311

Сделал список фильмов и список актеров в деталях. Переход с аргументами

2020-12-03 14:46 UTC, froimsonm commented on app/src/main/java/com/shukhaev/moviesaa/FragmentMoviesList.kt
> +        val title = movieAdapter.currentList[position].title
`movieAdapter.currentList[position]` дублируется, можно было бы 1 раз дергать лист по индексу

В связи с этим хочется теоретический вопрос обсудить, какая сложность в данном случае будет у операции поиска элемента по позиции в списке? Насколько весомой будет "оптимизация", если один раз вызывать `movieAdapter.currentList[position]`?

2020-12-03 14:47 UTC, froimsonm commented on app/src/main/java/com/shukhaev/moviesaa/MainActivity.kt
> +        APP_ACTIVITY = this
ой
весьма страшная конструкция
в идеале лучше избегать сохранения активити вне скоупа активити...

2020-12-03 14:48 UTC, froimsonm commented on app/src/main/java/com/shukhaev/moviesaa/MainActivity.kt
> +        APP_ACTIVITY = this
а какая была идея за этим?

2020-12-03 14:51 UTC, froimsonm commented on app/src/main/java/com/shukhaev/moviesaa/adapters/ActorAdapter.kt
> +    class ActorViewHolder(private val binding: ActorsListItemBinding) :
Не уверен, что нужно класть `ActorViewHolder` внутрь `ActorAdapter` класса
Для этого есть какая-то особая необходимость? Может я не  заметил... 🤔

2020-12-03 14:54 UTC, froimsonm commented on app/src/main/java/com/shukhaev/moviesaa/util/Util.kt
> +fun loadImage(url: String?, view: ImageView) {
лучше бы активити передавать параметром сюда, чтобы не хранить в глобальной переменной 😬

2020-12-03 14:54 UTC, ferr311 commented on app/src/main/java/com/shukhaev/moviesaa/MainActivity.kt
> +        APP_ACTIVITY = this
сделать утилитарную функцию для glide

2020-12-03 15:01 UTC, ferr311 commented on app/src/main/java/com/shukhaev/moviesaa/adapters/ActorAdapter.kt
> +    class ActorViewHolder(private val binding: ActorsListItemBinding) :
Если честно, я сакрального смысла этого не знаю, но во всех туториалах, что я видел, делают так.

2020-12-04 15:06 UTC, ferr311 commented
Пытаюсь создать кастомный рейтинг бар. Добавил класс и лайаут из примера, который скинул. Создал свой класс AppRatingBar.kt rating_bar.xml и attrs.xml проверяю все в test.xml Моя не отрисовывается , его отрисовывается. НЕ пойму как менять размеры imageView и цвет. Могу конечно просто сделать две иконки звезды разного цвета и менять их. Но проблема с размерами и вообще с отрисовкой не исчезнет :(

2020-12-07 07:26 UTC, froimsonm requested changes

2020-12-07 07:26 UTC, froimsonm commented on app/src/main/java/com/shukhaev/moviesaa/util/AppRatingBar.kt
> +    val progress: Int
`private val`?

2020-12-07 07:26 UTC, froimsonm commented on app/src/main/java/com/shukhaev/moviesaa/util/AppRatingBar.kt
> +        val star5: ShapeableImageView = rootView.findViewById(R.id.rating_bar_star5)
Почему-то кажется, что можно не указывать тип и просто писать `val star1 = rootView.findViewById(R.id.rating_bar_star1)`

2020-12-07 07:26 UTC, froimsonm commented on app/src/main/java/com/shukhaev/moviesaa/util/AppRatingBar.kt
> +        val star5: ShapeableImageView = rootView.findViewById(R.id.rating_bar_star5)
Почему-то обратил внимание, что star3, star4 и star5 в коде в итоге не используются
Это так и задумано? Ну то есть их либо нужно использовать где-то, либо не нужно инициализировать)

2020-12-07 07:26 UTC, froimsonm commented on app/src/main/java/com/shukhaev/moviesaa/util/AppRatingBar.kt
> +            progress = a.getInt(R.styleable.AppRatingBar_progress, 2)
а значение переменной `progress` на что-то влияет в итоге?)

2020-12-14 11:13 UTC, ferr311 commented
Поправил. Бар отрисовывается. Но теперь не хочет раскрашивать звезды когда передаю переменную colorFill или colorEmpty, а если вместо них передавать ресурс типа R.color.some_color то работает.

2020-12-20 13:53 UTC, froimsonm approved these changes

2020-12-21 11:56 UTC, merged